[[redirects]]
  from = "/netligit.json"
  to = "https://netlifygit.s3.ca-central-1.amazonaws.com/netligit.json"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
   
